/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.Calculos;
import javax.swing.JOptionPane;

/**
 *
 * @author arthu
 */


// NA TELA USE O BUTTON GROUP
// USE O jRadioButton3 PARA O BUTTON GROUP
public class Tela extends javax.swing.JFrame {
Calculos c = new Calculos();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTvalor1 = new javax.swing.JTextField();
        jTvalor2 = new javax.swing.JTextField();
        jBsomar = new javax.swing.JButton();
        jLresultado = new javax.swing.JLabel();
        jBsubtrair = new javax.swing.JButton();
        jBdividir = new javax.swing.JButton();
        jBmultiplicar = new javax.swing.JButton();
        jBporcentagem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRsomar2 = new javax.swing.JRadioButton();
        jRsubtrair2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite o primeiro numero: ");

        jLabel2.setText("Digite o segundo numero: ");

        jTvalor1.setColumns(5);
        jTvalor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvalor1ActionPerformed(evt);
            }
        });

        jTvalor2.setColumns(5);
        jTvalor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvalor2ActionPerformed(evt);
            }
        });

        jBsomar.setForeground(new java.awt.Color(0, 153, 153));
        jBsomar.setText("+");
        jBsomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsomarActionPerformed(evt);
            }
        });

        jLresultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLresultado.setText("0.00");

        jBsubtrair.setForeground(new java.awt.Color(0, 153, 153));
        jBsubtrair.setText("-");
        jBsubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsubtrairActionPerformed(evt);
            }
        });

        jBdividir.setBackground(new java.awt.Color(102, 102, 102));
        jBdividir.setForeground(new java.awt.Color(0, 153, 153));
        jBdividir.setText("/");
        jBdividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdividirActionPerformed(evt);
            }
        });

        jBmultiplicar.setForeground(new java.awt.Color(0, 153, 153));
        jBmultiplicar.setText("*");
        jBmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmultiplicarActionPerformed(evt);
            }
        });

        jBporcentagem.setForeground(new java.awt.Color(0, 153, 153));
        jBporcentagem.setText("%");
        jBporcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBporcentagemActionPerformed(evt);
            }
        });

        jLabel3.setText("Resultado:");

        buttonGroup2.add(jRsomar2);
        jRsomar2.setText("++");
        jRsomar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRsomar2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRsubtrair2);
        jRsubtrair2.setText("--");
        jRsubtrair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRsubtrair2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRsomar2)
                        .addGap(73, 73, 73)
                        .addComponent(jRsubtrair2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBsomar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBsubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBmultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jBporcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBdividir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBmultiplicar)
                    .addComponent(jBsomar)
                    .addComponent(jBporcentagem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsubtrair)
                    .addComponent(jBdividir)
                    .addComponent(jLresultado)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRsomar2)
                    .addComponent(jRsubtrair2))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsomarActionPerformed
        // TODO add your handling code here:
        c.setValor1(Double.valueOf(jTvalor1.getText()));
        c.setValor2(Double.valueOf(jTvalor2.getText()));
        jLresultado.setText(""+c.somar());
    }//GEN-LAST:event_jBsomarActionPerformed

    private void jBmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmultiplicarActionPerformed
        // TODO add your handling code here:
        c.setValor1(Double.valueOf(jTvalor1.getText()));
        c.setValor2(Double.valueOf(jTvalor2.getText()));
        jLresultado.setText(""+c.multiplicar());
    }//GEN-LAST:event_jBmultiplicarActionPerformed

    private void jBsubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsubtrairActionPerformed
        // TODO add your handling code here:
        c.setValor1(Double.valueOf(jTvalor1.getText()));
        c.setValor2(Double.valueOf(jTvalor2.getText()));
        jLresultado.setText(""+c.subtrair());
    }//GEN-LAST:event_jBsubtrairActionPerformed

    private void jBdividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdividirActionPerformed
        // TODO add your handling code here:
        c.setValor1(Double.valueOf(jTvalor1.getText()));
        c.setValor2(Double.valueOf(jTvalor2.getText()));
        jLresultado.setText(""+c.dividir());
    }//GEN-LAST:event_jBdividirActionPerformed

    private void jBporcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBporcentagemActionPerformed
        // TODO add your handling code here:
        c.setValor1(Double.valueOf(jTvalor1.getText()));
        jLresultado.setText(""+c.porcentagem());
    }//GEN-LAST:event_jBporcentagemActionPerformed

    private void jRsomar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRsomar2ActionPerformed
        // TODO add your handling code here:
        if(jRsomar2.isSelected()){
            if(jTvalor1.getText().equals("")){//equals verifica se o texto esta vazio.. "" como nao tem nada ele verifica
                JOptionPane.showMessageDialog(rootPane, "Campo Obrigatorio");
                jTvalor1.requestFocus();// voltar o cursor para o foco, exemplo esta selecionado para voltar ao valor1
            }else 
                if(jTvalor2.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Campo Obrigatorio");
                jTvalor2.requestFocus();
            }else {
            Calculos c = new Calculos(); // c variavel de instancia//objeto tipo calculo
            c.setValor1(Double.valueOf(jTvalor1.getText()));
            c.setValor2(Double.valueOf(jTvalor2.getText()));
            jLresultado.setText(""+c.somar2());
            jTvalor1.setText(""); // jT e o nome do botao do valor...
            jTvalor2.setText("");
            jTvalor1.requestFocus();// faz o cursor voltar ao valor1 no botao 1.
                }
        }
    }//GEN-LAST:event_jRsomar2ActionPerformed

    private void jRsubtrair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRsubtrair2ActionPerformed
        // TODO add your handling code here:
        if(jRsubtrair2.isSelected()){
            if(jTvalor1.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Campo Obrigatorio");
                jTvalor1.requestFocus();
            }else 
                if(jTvalor2.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Campo Obrigatorio");
                jTvalor2.requestFocus();
            }else {      
            Calculos c = new Calculos();
            c.setValor1(Double.valueOf(jTvalor1.getText()));
            c.setValor2(Double.valueOf(jTvalor2.getText()));
            jLresultado.setText(""+c.subtrair2());
            jTvalor1.setText(""); // jT e o nome do botao do valor...
            jTvalor2.setText("");
            jTvalor1.requestFocus();// faz o cursor voltar ao valor1 no botao 1.
                }
        }
    }//GEN-LAST:event_jRsubtrair2ActionPerformed

    private void jTvalor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvalor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTvalor2ActionPerformed

    private void jTvalor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvalor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTvalor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBdividir;
    private javax.swing.JButton jBmultiplicar;
    private javax.swing.JButton jBporcentagem;
    private javax.swing.JButton jBsomar;
    private javax.swing.JButton jBsubtrair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JRadioButton jRsomar2;
    private javax.swing.JRadioButton jRsubtrair2;
    private javax.swing.JTextField jTvalor1;
    private javax.swing.JTextField jTvalor2;
    // End of variables declaration//GEN-END:variables
}
